server:
  port: 8082

spring:
  web:
    locale: en_US
  lifecycle:
    timeout-per-shutdown-phase: 30s
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    hikari:
      username: "${DB_USER}"
      password: "${DB_PASSWORD}"
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
