-- DROP TABLE IF EXISTS account;
-- DROP TABLE IF EXISTS order_product;
-- DROP TABLE IF EXISTS product;
-- DROP TABLE IF EXISTS order;


CREATE TABLE account
(
    id       UUID NOT NULL
        PRIMARY KEY,
    address  VARCHAR(255),
    email    VARCHAR(255),
    name     VARCHAR(255),
    password VARCHAR(255),
    phone    VARCHAR(255),
    role     VARCHAR(255)
);

ALTER TABLE account
    OWNER TO og;

CREATE TABLE product
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    price           DOUBLE PRECISION,
    stock           INTEGER,
    image_full_path VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (id)
);

ALTER TABLE product
    OWNER TO og;

CREATE TABLE order_product
(
    quantity   INTEGER NOT NULL,
    order_id   BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    CONSTRAINT pk_order_product PRIMARY KEY (order_id, product_id)
);



ALTER TABLE order_product
    OWNER TO og;


CREATE TABLE orders
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date              DATE,
    customer_id       BIGINT,
    transaction_state INTEGER,
    status            VARCHAR(255),
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE order_product
    ADD CONSTRAINT FK_ORDER_PRODUCT_ON_ORDER FOREIGN KEY (order_id) REFERENCES "order" (id);

ALTER TABLE order_product
    ADD CONSTRAINT FK_ORDER_PRODUCT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE "orders"
    OWNER TO og;