version: '3.8'

services:
  vm_app_database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/initdb.sh


  vm_app:
    image: docker.io/oxyac/vending-machine:0.0.1
    environment:
      - DB_NAME=vending_machine
      - DB_PASSWORD=vending_machine
      - DB_PORT=5432
      - DB_USER=vending_machine
      - DB_HOST=vm_app_database
    depends_on:
      - vm_app_database
